# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42ed774285a526cd38fd176d0f8a88744cebde332cc11132372b84a0aef7bb5d69664eb2de931a2b5d131e2f77045d016ba86d170de4b3770f4a560fc224e9c6

test:
  secret_key_base: 9909f596189a1808f76a603335f6fdac7cb2ef03b8202d150abb55d6e809ab16c2885b14fffdddc92baedcaf46395c67a072d0dd48753af2e8109caed0124ec6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
